language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml

after_script:
  - sh .travis.coverage.sh

matrix:
  allow_failures:
    - php: hhvm
